export const keyActions: {
  [key: string]: { animation: string; node: string };
} = {
  KeyA: { animation: "press_a_key", node: "a_key" },
  KeyB: { animation: "press_b_key", node: "b_key" },
  KeyC: { animation: "press_c_key", node: "c_key" },
  KeyD: { animation: "press_d_key", node: "d_key" },
  KeyE: { animation: "press_e_key", node: "e_key" },
  KeyF: { animation: "press_f_key", node: "f_key" },
  KeyG: { animation: "press_g_key", node: "g_key" },
  KeyH: { animation: "press_h_key", node: "h_key" },
  KeyI: { animation: "press_i_key", node: "i_key" },
  KeyJ: { animation: "press_j_key", node: "j_key" },
  KeyK: { animation: "press_k_key", node: "k_key" },
  KeyL: { animation: "press_l_key", node: "l_key" },
  KeyM: { animation: "press_m_key", node: "m_key" },
  KeyN: { animation: "press_n_key", node: "n_key" },
  KeyO: { animation: "press_o_key", node: "o_key" },
  KeyP: { animation: "press_p_key", node: "p_key" },
  KeyQ: { animation: "press_q_key", node: "q_key" },
  KeyR: { animation: "press_r_key", node: "r_key" },
  KeyS: { animation: "press_s_key", node: "s_key" },
  KeyT: { animation: "press_t_key", node: "t_key" },
  KeyU: { animation: "press_u_key", node: "u_key" },
  KeyV: { animation: "press_v_key", node: "v_key" },
  KeyW: { animation: "press_w_key", node: "w_key" },
  KeyX: { animation: "press_x_key", node: "x_key" },
  KeyY: { animation: "press_y_key", node: "y_key" },
  KeyZ: { animation: "press_z_key", node: "z_key" },
  Digit0: { animation: "press_0_key", node: "zero_key" },
  Digit1: { animation: "press_1_key", node: "one_key" },
  Digit2: { animation: "press_2_key", node: "two_key" },
  Digit3: { animation: "press_3_key", node: "three_key" },
  Digit4: { animation: "press_4_key", node: "four_key" },
  Digit5: { animation: "press_5_key", node: "five_key" },
  Digit6: { animation: "press_6_key", node: "six_key" },
  Digit7: { animation: "press_7_key", node: "seven_key" },
  Digit8: { animation: "press_8_key", node: "eight_key" },
  Digit9: { animation: "press_9_key", node: "nine_key" },
  F1: { animation: "press_f1_key", node: "f1_key" },
  F2: { animation: "press_f2_key", node: "f2_key" },
  F3: { animation: "press_f3_key", node: "f3_key" },
  F4: { animation: "press_f4_key", node: "f4_key" },
  F5: { animation: "press_f5_key", node: "f5_key" },
  F6: { animation: "press_f6_key", node: "f6_key" },
  F7: { animation: "press_f7_key", node: "f7_key" },
  F8: { animation: "press_f8_key", node: "f8_key" },
  F9: { animation: "press_f9_key", node: "f9_key" },
  F10: { animation: "press_f10_key", node: "f10_key" },
  F11: { animation: "press_f11_key", node: "f11_key" },
  F12: { animation: "press_f12_key", node: "f12_key" },
  F13: { animation: "press_f12_key", node: "print_key" },
  Escape: { animation: "press_escape_key", node: "esc_key" },
  Backquote: { animation: "press_tilde_key", node: "tilde_key" },
  Minus: { animation: "press_minus_key", node: "minus_key" },
  Equal: { animation: "press_equal_key", node: "equal_key" },
  Backspace: { animation: "press_backspace_key", node: "backspace_key" },
  Tab: { animation: "press_tab_key", node: "tab_key" },
  Backslash: { animation: "press_backslash_key", node: "backslash_key" },
  CapsLock: { animation: "press_caps_lock_key", node: "caps_lock_key" },
  Enter: { animation: "press_enter_key", node: "enter_key" },
  ShiftLeft: { animation: "press_shift_left_key", node: "shift_left_key" },
  ShiftRight: { animation: "press_shift_right_key", node: "shift_right_key" },
  ControlLeft: { animation: "press_ctrl_left_key", node: "ctrl_left_key" },
  ControlRight: { animation: "press_ctrl_right_key", node: "ctrl_right_key" },
  MetaLeft: { animation: "press_meta_left_key", node: "meta_left_key" },
  AltLeft: { animation: "press_alt_left_key", node: "alt_left_key" },
  AltRight: { animation: "press_alt_right_key", node: "alt_right_key" },
  Space: {
    animation: "press_space_bar",
    node: "space_bar_key",
  },
  BracketLeft: {
    animation: "press_bracket_left_key",
    node: "bracket_left_key",
  },
  BracketRight: {
    animation: "press_bracket_right_key",
    node: "bracket_right_key",
  },
  Semicolon: { animation: "press_semicolon_key", node: "semicolon_key" },
  Quote: { animation: "press_quote_key", node: "quote_key" },
  Comma: { animation: "press_comma_key", node: "comma_key" },
  Period: { animation: "press_period_key", node: "period_key" },
  Slash: { animation: "press_slash_key", node: "slash_key" },
  ArrowLeft: { animation: "press_arrow_left_key", node: "arrow_left_key" },
  ArrowRight: { animation: "press_arrow_right_key", node: "arrow_right_key" },
  ArrowUp: { animation: "press_arrow_up_key", node: "arrow_up_key" },
  ArrowDown: {
    animation: "press_arrow_down_key",
    node: "arrow_down_key",
  },
  Delete: { animation: "press_delete_key", node: "delete_key" },
  PageUp: { animation: "press_pg_up_key", node: "pg_up_key" },
  PageDown: { animation: "press_pg_down_key", node: "pg_down_key" },
  End: { animation: "press_end_key", node: "end_key" },
};
